[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && pnpm install && pnpm build && pnpm prisma generate && pnpm prisma migrate deploy"

[deploy]
startCommand = "cd apps/backend && pnpm start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"