[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && pnpm build"

[deploy]
startCommand = "cd apps/backend && pnpm start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 