[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && pnpm install && pnpm build && pnpm prisma generate"

[deploy]
startCommand = "cd apps/backend && pnpm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"